SNR-4-create-navbar-and-connect-with-strapi
lhanc-itcrowd/rampup-frontend pull request #2
Opened 2023-10-20 18:50 UTC by yamiltauil

2023-10-23 12:52 UTC, lhanc-itcrowd requested changes

2023-10-23 12:52 UTC, lhanc-itcrowd commented on src/app/components/button.tsx
> +		<div>
Este div no es necesario.

2023-10-23 12:52 UTC, lhanc-itcrowd commented on src/app/components/navbar.tsx
> +		const res = await fetch("http://localhost:1337/api/navbars");
Podemos usar una variable de entorno aca para la url base de la api?

2023-10-23 12:52 UTC, lhanc-itcrowd commented on src/app/components/navbar.tsx
> +		setHide(!hide);
Esto no es necesario que lo cambies porque no está mal en sí pero para la próxima lo óptimo sería hacer
```suggestion
		setHide(current => !current);
```
Pasando una funcion al setter tenes acceso al valor actual posta posta con toda seguridad.
La otra opción, según el equipo de React puede en algún caso raro tomarte valores desactualizados

> Using the functional update form ensures that you are always working with the latest state.
React might batch state updates, and you can't guarantee that the state is immediately updated. This can lead to unexpected behavior, especially when dealing with multiple state updates in the same function.

2023-10-23 12:52 UTC, lhanc-itcrowd commented on src/app/components/button.tsx
> +				type="submit"
Para hacerlo reutilizable este type te debería venir por props.

2023-10-23 12:52 UTC, lhanc-itcrowd commented on src/app/components/navbar.tsx
> +							: "undefined"}
Acá te quedo undefined como string.
Lo ideal sería poner como valor `null`

2023-10-23 12:52 UTC, lhanc-itcrowd commented on src/app/components/navbar.tsx
> +							type="submit"
El tipo `submit` es para cuando estás trabajando en un formulario (dentro de tags `form`) y querés enviar la información de los campos del mismo.
Para este caso el tipo correcto es "button".

2023-10-23 12:52 UTC, lhanc-itcrowd commented on src/app/components/navbar.tsx
> +	const handleclick = (e: React.MouseEvent<HTMLButtonElement>) => {
Bien al tipar aca 👍 

Sugerencia para la próxima: un nombre de método más descriptivo, menos genérico. Para qué tipo de elemento que fue clickeado es este handler?

`handleBurgerButtonClick`

y otra alternativa es describir la acción como 

`toggleNavbar`, `toggleNavbarOpen`, `toggleNavbarVisibility`

al leer un nombre de función descriptivo entiendo lo que hace con sólo leerlo, sin tener que buscar más contexto en el código.

2023-10-23 12:52 UTC, lhanc-itcrowd commented on src/app/components/navbar.tsx
> +									<p key={id} className="ml-4 mt-4 hover:cursor-pointer">
Necesitaríamos que desde el back nos llegue también la URL a la que van estos items. No importa que te den 404 pero debería venir la URL y estos ser ser elementos `Link` importados de `next/link`

2023-10-23 18:49 UTC, yamiltauil commented on src/app/components/navbar.tsx
> +									<p key={id} className="ml-4 mt-4 hover:cursor-pointer">
me falta agregarle esto al back

2023-10-24 12:08 UTC, lhanc-itcrowd approved these changes

2023-10-24 13:43 UTC, merged